spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/project?useTimezone=true&serverTimezone=UTC
    username: root
    password: 1nd2gw3jmm
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 626888405475-bgrp2mtgnvvveo38kqshl5egit3p1ig6.apps.googleusercontent.com
            client-secret: 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
      resourceserver:
        jwt:
          issuer-uri: https://accounts.google.com